// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// similarity_Rcpp
NumericMatrix similarity_Rcpp(CharacterVector seq1, CharacterVector seq2);
RcppExport SEXP _alignSeq_similarity_Rcpp(SEXP seq1SEXP, SEXP seq2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type seq2(seq2SEXP);
    rcpp_result_gen = Rcpp::wrap(similarity_Rcpp(seq1, seq2));
    return rcpp_result_gen;
END_RCPP
}
// scoring_Rcpp
NumericMatrix scoring_Rcpp(int d, CharacterVector seq1, CharacterVector seq2);
RcppExport SEXP _alignSeq_scoring_Rcpp(SEXP dSEXP, SEXP seq1SEXP, SEXP seq2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type seq2(seq2SEXP);
    rcpp_result_gen = Rcpp::wrap(scoring_Rcpp(d, seq1, seq2));
    return rcpp_result_gen;
END_RCPP
}
// getAlignement_Rcpp
List getAlignement_Rcpp(int d, CharacterVector seq1, CharacterVector seq2);
RcppExport SEXP _alignSeq_getAlignement_Rcpp(SEXP dSEXP, SEXP seq1SEXP, SEXP seq2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type seq2(seq2SEXP);
    rcpp_result_gen = Rcpp::wrap(getAlignement_Rcpp(d, seq1, seq2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_alignSeq_similarity_Rcpp", (DL_FUNC) &_alignSeq_similarity_Rcpp, 2},
    {"_alignSeq_scoring_Rcpp", (DL_FUNC) &_alignSeq_scoring_Rcpp, 3},
    {"_alignSeq_getAlignement_Rcpp", (DL_FUNC) &_alignSeq_getAlignement_Rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_alignSeq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
