# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Similarity matrix algorithm using C++
#'
#' @param seq1 first sequence
#' @param seq1 second sequence
#' @param n length of first sequence
#' @param m length of second sequence
#' @return a similarity matrix
#' @export
similarity_Rcpp <- function(seq1, seq2) {
    .Call(`_alignSeq_similarity_Rcpp`, seq1, seq2)
}

#' Score matrix algorithm using C++
#'
#'@param d deletion
#' @param seq1 first sequence
#' @param seq1 second sequence
#' @param n length of first sequence
#' @param m length of second sequence
#' @return a similarity matrix
#' @export
scoring_Rcpp <- function(d, seq1, seq2) {
    .Call(`_alignSeq_scoring_Rcpp`, d, seq1, seq2)
}

#'get Alignement algorithm using C++
#'
#'@param d deletion
#' @param seq1 first sequence
#' @param seq1 second sequence
#' @param n length of first sequence
#' @param m length of second sequence
#' @return a similarity matrix
#' @export
getAlignement_Rcpp <- function(d, seq1, seq2) {
    .Call(`_alignSeq_getAlignement_Rcpp`, d, seq1, seq2)
}

